# Configuration for the Telegram chatbot models
models:
  generative:
    model_name: "chatbot.models.Gemini"
    model_params:
      name: "gemini-1.5-flash-latest"

  embedding:
    model_name: "chatbot.models.OpenAIEmbedding"
    model_params:
      name: "text-embedding-3-large"

# Intent classifier uses generative model above
intent-classifier:
  model_config:
    temperature: 0.4
    top_p: 0.2
    top_k: 10

semantic-search:
  chunk_size: 400
  chunk_overlap: 10
