# Configuration for the Telegram chatbot models
models:
  generative:
    model_name: "chatbot.models.Gemini" # Gemini, OpenAIGPT
    model_params:
      name: "gemini-1.5-flash-latest" # Match the model

  embedding:
    model_name: "chatbot.models.OpenAIEmbedding" # OpenAIEmbedding, GeminiEmbedding
    model_params:
      name: "text-embedding-3-large" # Match the model

# Intent classifier uses generative model above
intent-classifier:
  model_config:
    temperature: 0.4
    top_p: 0.2
    top_k: 10

semantic-search:
  chunk_size: 400
  chunk_overlap: 10

feedback-system:
  active: true
  file_path: "feedbacks.sqlite"